#!/bin/bash

SCRIPT="install"
HOME=$HOME
PACKAGE=$(pwd)
ORIG=0
TARGET_RC=".vimrc"
ORIG_RC=".vimrc.orig"
TARGET_DATA=".vim"
ORIG_DATA=".vim.orig"
REAL_RC="$HOME/$TARGET_DATA/vimrc"
SCRIPT_PATH="$TARGET_DATA/$SCRIPT"
GIT_PATH="$TARGET_DATA/.git"
CTAGS=$(which ctags)

if [ "$CTAGS" == "" ] ; then
    echo
    echo ctags is not installed. please install it manually:
    echo '  $ cd download/'
    echo '  $ tar -xzf ctags-5.8.tar.gz'
    echo '  $ cd ctags-5.8'
    echo '  $ ./configure ; make ; sudo make install'
    echo
    exit 1
fi

cd $HOME

if [ -e "$TARGET_RC" ] ; then
    if [ -L "$TARGET_RC" ] ; then
        rm -f $TARGET_RC
    else
        mv $TARGET_RC $ORIG_RC
        ORIG=1
    fi
fi

if [ -e "$TARGET_DATA" ] ; then
    if [ -e "$ORIG_DATA" ] ; then
        echo Found existing original data in \'$ORIG_DATA\'. Skipping data backup...
    else
        echo Found existing vim data in \'$TARGET_DATA\'. Backing up to \'$ORIG_DATA\'...
        mv $TARGET_DATA $ORIG_DATA
    fi
fi

if [ -e "$GIT_PATH" ] ; then
    rm -rf $GIT_PATH
fi

cp -r $PACKAGE $TARGET_DATA
ln -s $REAL_RC $TARGET_RC

if [ -e "$GIT_PATH" ] ; then
    rm -rf $GIT_PATH
fi

if [ -e "$SCRIPT_PATH" ] ; then
    rm $SCRIPT_PATH
fi

if [[ ("$ORIG" == "1" ) || (-e "$ORIG_RC") ]] ; then
    echo "source ~/$ORIG_RC" >> $REAL_RC
fi
